DELETE FROM PROPRIETE;
DELETE FROM SECHE_LINGE;
DELETE FROM LAVE_LINGE;
DELETE FROM CAFETIERE;
DELETE FROM ELECTROMENAGER;
DELETE FROM PERSONNE;

INSERT INTO PERSONNE(NOM, PRENOM) VALUES('Dupont', 'Albert');
INSERT INTO PERSONNE(NOM, PRENOM) VALUES('Bacle', 'Ginés');
INSERT INTO PERSONNE(NOM, PRENOM) VALUES('Moralés', 'Jean');

INSERT INTO CAFETIERE(MARQUE, REFERENCE, PRIX, PUISSANCE, PRESSION) VALUES('Proline', 'CM125B', 9.99, 870, null);
INSERT INTO CAFETIERE(MARQUE, REFERENCE, PRIX, PUISSANCE, PRESSION) VALUES('Krups Krups', 'EA9010', 1169, null, 15);
INSERT INTO CAFETIERE(MARQUE, REFERENCE, PRIX, PUISSANCE, PRESSION) VALUES('Kenwood', 'COX750BK', 89.99, 1000, null);

INSERT INTO LAVE_LINGE(MARQUE, REFERENCE, PRIX, CONSOMMATION_ENERGIE, CAPACITE_LAVAGE, VITESSE_ESSORAGE_MAX) VALUES('Indesit', 'XWA71452WFR', 299.99, 192, 7, 1400);
INSERT INTO LAVE_LINGE(MARQUE, REFERENCE, PRIX, CONSOMMATION_ENERGIE, CAPACITE_LAVAGE, VITESSE_ESSORAGE_MAX) VALUES('LG', 'LSWD100W SIGNATURE', 3499, null, 7, 1600);
INSERT INTO LAVE_LINGE(MARQUE, REFERENCE, PRIX, CONSOMMATION_ENERGIE, CAPACITE_LAVAGE, VITESSE_ESSORAGE_MAX) VALUES('Faure', 'FWF10120PS', 329, 190, 10, 1200);

INSERT INTO SECHE_LINGE(MARQUE, REFERENCE, PRIX, CONSOMMATION_ENERGIE, CAPACITE_SECHAGE, TYPE_SECHE_LINGE) VALUES('Candy', 'CSV9DF', 199.99, 636, 9, 'Evacuation');
INSERT INTO SECHE_LINGE(MARQUE, REFERENCE, PRIX, CONSOMMATION_ENERGIE, CAPACITE_SECHAGE, TYPE_SECHE_LINGE) VALUES('Miele', 'PT 5136 INOX', 2899, null, 6.5, 'Evacuation');
INSERT INTO SECHE_LINGE(MARQUE, REFERENCE, PRIX, CONSOMMATION_ENERGIE, CAPACITE_SECHAGE, TYPE_SECHE_LINGE) VALUES('Samsung', 'DV80M52103 METAL GREY', 899, 176, 8, 'Condensation');

INSERT INTO PROPRIETE(ID_PERSONNE, ID_ELECTROMENAGER)
    SELECT P.ID_PERSONNE, E.ID_ELECTROMENAGER FROM ELECTROMENAGER E, PERSONNE P
            WHERE P.NOM = 'Moralés' AND (E.MARQUE = 'Faure' OR E.MARQUE = 'Proline');

INSERT INTO PROPRIETE(ID_PERSONNE, ID_ELECTROMENAGER)
    SELECT P.ID_PERSONNE, E.ID_ELECTROMENAGER FROM ELECTROMENAGER E, PERSONNE P
            WHERE P.NOM = 'Dupont' AND (E.MARQUE = 'Kenwood' OR E.MARQUE = 'LG' OR E.MARQUE = 'Miele');

INSERT INTO PROPRIETE(ID_PERSONNE, ID_ELECTROMENAGER)
    SELECT P.ID_PERSONNE, E.ID_ELECTROMENAGER FROM ELECTROMENAGER E, PERSONNE P
            WHERE P.NOM = 'Bacle' AND (E.MARQUE = 'LG' OR E.MARQUE = 'Miele');

            