DROP SCHEMA If EXISTS TMP CASCADE;
CREATE SCHEMA TMP;










DROP TABLE If EXISTS TMP.CARACTERISATION;
DROP TABLE If EXISTS TMP.MOT_CLEF;
DROP TABLE If EXISTS TMP.EMPRUNT;
DROP TABLE If EXISTS TMP.EXEMPLAIRE;
DROP TABLE If EXISTS TMP.LIVRE;
DROP TABLE If EXISTS TMP.ABONNE;










CREATE TABLE TMP.ABONNE(
	NUMERO_ABONNE INTEGER,
	NOM VARCHAR(20) NOT NULL,
	PRENOM VARCHAR(20),
	AGE INTEGER,
	TARIF REAL,
	REDUCTION REAL,
	VILLE VARCHAR(30),
	CONSTRAINT ABONNE_PK PRIMARY KEY (NUMERO_ABONNE),
	CONSTRAINT AGE_DK CHECK (AGE BETWEEN 0 AND 120)
);





CREATE TABLE TMP.LIVRE(
	ISBN VARCHAR(20),
	TITRE VARCHAR(50) NOT NULL,
	SIECLE INTEGER CHECK (SIECLE BETWEEN 0 AND 21),
	CATEGORIE VARCHAR(20),
	CONSTRAINT LIVRE_PK PRIMARY KEY (ISBN)
);





CREATE TABLE TMP.EXEMPLAIRE(
	NUMERO INTEGER,
	DATE_ACHAT DATE,
	PRIX REAL,
	CODE_PRET VARCHAR(20),
	ETAT VARCHAR(15) CHECK (ETAT IN ('BON', 'ABIME', 'EN_REPARATION')),
	ISBN VARCHAR(20),
	CONSTRAINT EXEMPLAIRE_PK PRIMARY KEY (NUMERO),
	CONSTRAINT EXEMPLAIRETOLIVRE_FK FOREIGN KEY (ISBN) REFERENCES TMP.LIVRE(ISBN),
	CONSTRAINT CODE_PRET_DK CHECK (CODE_PRET IN ('EXCLU', 'EMPRUNTABLE', 'CONSULTABLE')) 
);





CREATE TABLE TMP.EMPRUNT(
	NUMERO_ABONNE INTEGER,
	NUMERO INTEGER,
	DATE_EMPRUNT DATE,
	DATE_RETOUR DATE,
	DATE_RETOUR_REEL DATE,
	NB_RELANCE INTEGER CHECK (NB_RELANCE IN (1, 2, 3)),
	CONSTRAINT EMPRUNT_PK PRIMARY KEY (NUMERO_ABONNE, NUMERO, DATE_EMPRUNT),
	CONSTRAINT EMPRUNTTOABONNE_FK FOREIGN KEY (NUMERO_ABONNE) REFERENCES TMP.ABONNE(NUMERO_ABONNE),
	CONSTRAINT EMPRUNTTOEXEMPLAIRE_FK FOREIGN KEY (NUMERO) REFERENCES TMP.EXEMPLAIRE(NUMERO)
);





CREATE TABLE TMP.MOT_CLEF (
	MOT VARCHAR(20),
	CONSTRAINT MOT_CLEF_PK PRIMARY KEY (MOT)
);





CREATE TABLE TMP.CARACTERISATION(
	ISBN VARCHAR(20),
	MOT VARCHAR(20),
	CONSTRAINT CARACT_PK PRIMARY KEY (ISBN, MOT),
	CONSTRAINT CARACTTOLIVRE_FK FOREIGN KEY (ISBN) REFERENCES TMP.LIVRE(ISBN),
	CONSTRAINT CARACTTOMOT_CLEF_FK FOREIGN KEY (MOT) REFERENCES TMP.MOT_CLEF(MOT)
);
